### ISSUE TITLE
Typo in datastream public properties

### ISSUE THREAD

**Issue by RSLi** [MD2Korg/CerebralCortex-Kernel#5]
https://github.com/MD2Korg/CerebralCortex/blob/fa92dd3f05fa76e91c7d588058ace55aa6864978/cerebralcortex/core/datatypes/datastream.py#L108

Though this property (stream's `start_time`) doesn't seem to be used much, but I believe this is unintended.

**Comment by nasirali1** [comment]
Thank, we have restructured the whole code and documented it. Have a look at 3.1 branch
